feat: complete redesign of settings user story
Iconica-Development/flutter_settings pull request #19
Opened 2024-10-28 10:55 UTC by FlutterJoey

2025-04-08 07:02 UTC, freekvandeven commented on packages/firebase_settings_repository/pubspec.yaml
> +    version: ^1.0.0
set it to ^7.0.0

2025-04-08 07:02 UTC, freekvandeven commented on packages/flutter_settings/lib/src/config/controls/base.dart
this file could use some /// comments

2025-04-08 07:03 UTC, freekvandeven commented on packages/flutter_settings/lib/src/config/controls/controls.dart
could use some doc comments

2025-04-08 07:04 UTC, freekvandeven commented on packages/flutter_settings/lib/src/config/controls/group.dart
some doc comments

2025-04-08 07:04 UTC, freekvandeven commented on packages/flutter_settings/lib/src/config/controls/radio.dart
> +          for (var option in options)
...[]

2025-04-08 07:05 UTC, freekvandeven commented on packages/flutter_settings/lib/src/config/controls/text.dart
> +    Theme.of(context);
ok, this is doing???

2025-04-08 07:05 UTC, freekvandeven commented on packages/flutter_settings/lib/src/config/options.dart
> +  SettingsOptions({
const

2025-04-08 07:35 UTC, freekvandeven requested changes

2025-04-08 07:35 UTC, freekvandeven commented on packages/settings_repository/lib/src/local_settings_repository.dart
> +  Future<void> saveSingleSettingForNamespace<T>(
shouldn't these have /// comments or is the linter not added?

2025-04-08 07:35 UTC, freekvandeven commented on packages/settings_repository/analysis_options.yaml
add the component analysis

2025-04-08 07:35 UTC, freekvandeven commented on packages/settings_repository/lib/settings_repository.dart
> +///
nice comment

2025-04-08 07:35 UTC, freekvandeven commented on packages/settings_repository/README.md
link to the main README

2025-04-08 07:35 UTC, freekvandeven commented on packages/settings_repository/CHANGELOG.md
link to the main Changelog

2025-04-08 07:35 UTC, freekvandeven commented on packages/flutter_settings/pubspec.yaml
> +    version: ^1.0.0
point to ^7.0.0

2025-04-08 07:35 UTC, freekvandeven commented on packages/flutter_settings/lib/src/util/scope.dart
> +///
small comment explaining the use

2025-04-08 07:35 UTC, freekvandeven commented on packages/flutter_settings/lib/src/user_story.dart
> +  String userId,
userId should be namespace

2025-04-08 07:35 UTC, freekvandeven commented on packages/flutter_settings/lib/src/user_story.dart
> +  String userId,
also maybe named parameters

2025-04-08 07:35 UTC, freekvandeven commented on packages/flutter_settings/lib/src/ui/defaults/default_base_screen.dart
> +        title: const Text("Settings"),
Could maybe also be in the translations so the defaults can still have translated strings

2025-04-08 07:35 UTC, freekvandeven commented on packages/flutter_settings/lib/src/config/controls/toggle.dart
> +  ToggleControlConfig({
this could all be const if you make SettingsControlConfig const and follow the classes that extend it

2025-04-08 09:14 UTC, FlutterJoey commented on .pre-commit-config.yaml
This is a good addition for future implementations, I specifically want to avoid delays on this for future packages. I could remove it for now.

2025-04-08 09:16 UTC, FlutterJoey commented on README.md
We need to add this back, currently there are no GIF's or other documentation. This should be added back

2025-04-09 06:59 UTC, FlutterJoey commented on packages/firebase_settings_repository/README.md
I don't think the individual packages should be linked to the same README. The readme's should be different.

2025-04-09 06:59 UTC, FlutterJoey commented on packages/flutter_settings/lib/src/config/options.dart
> +  SettingsOptions({
cannot be const, localSettingsRepository is a factory constructor.

2025-04-09 06:59 UTC, FlutterJoey commented on packages/flutter_settings/lib/src/ui/defaults/default_base_screen.dart
> +        title: const Text("Settings"),
Given that this would the only translated text, I am going to say that anyone should just use their own base screen if they want a translated string

2025-04-09 06:59 UTC, FlutterJoey commented on packages/flutter_settings/lib/src/ui/settings_screen.dart
> +                  const Text("Save"),
There is not really any in-component texts except in the two builders. I would not like to increase the option depth.

2025-04-09 07:34 UTC, freekvandeven requested changes

2025-04-09 07:34 UTC, freekvandeven commented on .pre-commit-config.yaml
> +    ]
include the 2 other packages and the other example apps

2025-04-09 07:34 UTC, freekvandeven commented on README.md
> +> TODO: GIF
are we adding this before releasing version 7?

2025-04-09 07:34 UTC, freekvandeven commented on melos.yaml
> +name: flutter_locations
put it back to flutter_settings

2025-04-09 07:34 UTC, freekvandeven commented on packages/device_settings_repository/README.md
link to central README.md

2025-04-09 07:34 UTC, freekvandeven commented on packages/device_settings_repository/analysis_options.yaml
> +    public_member_api_docs: false
I would prefer this is removed

2025-04-09 07:34 UTC, freekvandeven commented on packages/firebase_settings_repository/README.md
point to the main README.md

2025-04-09 07:34 UTC, freekvandeven commented on packages/firebase_settings_repository/analysis_options.yaml
revert the change

2025-04-09 07:34 UTC, freekvandeven commented on packages/flutter_settings/lib/src/config/controls/base.dart
> +  ///
maybe also explain that the @build should not be overridden in the doc comment

2025-04-09 07:34 UTC, freekvandeven commented on packages/flutter_settings/lib/src/config/controls/base.dart
> +  ///
comment explaining you should use this buildSetting to provide custom UI and logic for your SettingsControlGroup

2025-04-09 07:34 UTC, freekvandeven commented on packages/settings_repository/README.md
this should point to the main README.md

2025-04-09 14:11 UTC, freekvandeven approved these changes

2025-05-21 08:04 UTC, merged